# Generated by Django 4.1.5 on 2023-02-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MetropolitanArea',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assets_misc',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='assets_property',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='assets_savings',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='assets_total',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='current_pfm',
            field=models.CharField(
                choices=[
                    ('mint', 'Mint'),
                    ('rocket money', 'Rocket Money'),
                    ('quicken', 'Quicken'),
                    ('chime', 'Chime'),
                    ('splitwise', 'Splitwise'),
                    ('pen paper', 'Pen & paper'),
                    ('none', 'None'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_housing',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_other_fixed',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='exp_other_variable',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[
                    ('male', 'Male'),
                    ('female', 'Female'),
                    ('transgender', 'Transgender'),
                    ('prefer_not_to_say', 'Prefer not to say'),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_primary_annual',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_primary_tax_fed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_primary_tax_state',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_secondary_monthly',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_secondary_tax_fed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_secondary_tax_state',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_total_annual',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_variable_monthly',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_variable_tax_fed',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='inc_variable_tax_state',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(
                choices=[
                    (1, 'Individual Contributor, Associate'),
                    (2, 'Individual Contributor'),
                    (3, 'Individual Contributor, Senior'),
                    (4, 'Individual Contributor, Staff'),
                    (5, 'Individual Contributor, Principal'),
                    (6, 'Manager'),
                    (7, 'Director'),
                    (8, 'Director, Senior'),
                    (9, 'VP'),
                    (10, 'VP, Senior'),
                    (11, 'C-Suite'),
                    (12, 'Founder'),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='lia_credit_card',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='lia_loans',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='lia_misc',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='lia_total',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='net_monthly_profit_loss',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='net_worth',
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=None, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='sav_market',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='sav_retirement',
            field=models.DecimalField(
                decimal_places=2, default=None, max_digits=12, null=True
            ),
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                (
                    'industry',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='job_titles',
                        to='authentication.industry',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='authentication.industry',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='authentication.jobtitle',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='metro',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='authentication.metropolitanarea',
            ),
        ),
    ]
