# Generated by Django 4.1.5 on 2023-03-09 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'authentication',
            '0002_alter_user_managers_remove_jobtitle_industry_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
