# Generated by Django 4.1.5 on 2023-03-10 17:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatUser',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('chat_engine_id', models.BigIntegerField()),
                ('username', models.CharField(max_length=24, unique=True)),
                ('secret', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('agreed_to_terms', models.BooleanField(default=False)),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='chat_user',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
