# Generated by Django 4.1.5 on 2023-03-12 21:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_chatuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatuser',
            name='password',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='chatuser',
            name='secret',
            field=models.CharField(editable=False, max_length=128),
        ),
    ]
