# Generated by Django 4.1.5 on 2023-03-14 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_chatuser_password_alter_chatuser_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedMisconduct',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('acknowledged_by_staff', models.BooleanField(default=False)),
                (
                    'defendant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cases_as_defendant',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'plaintiff',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cases_as_plaintiff',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
